<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = Carbon::create(2024, 11, 30, 0, 0, 0);

        DB::table('menu_items')->insert([
            // Kategori 1: Makanan Utama
            [
                'menu_item_id' => 1,
                'menu_name' => 'Soto Bandung',
                'price' => 15000.00,
                'stock' => 50,
                'status' => 1,
                'image' => 'uploads/menu/Soto_Bandung.jpg',
                'description' => 'Soto khas Bandung dengan kuah bening dan daging sapi.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 2,
                'menu_name' => 'Mie Kocok Bandung',
                'price' => 10000.00,
                'stock' => 45,
                'status' => 1,
                'image' => 'uploads/menu/Mie_Kocok_Bandung.jpg',
                'description' => 'Mie kocok khas Bandung dengan kuah kaldu sapi yang gurih.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 3,
                'menu_name' => 'Nasi Goreng Spesial',
                'price' => 18000.00,
                'stock' => 40,
                'status' => 1,
                'image' => 'uploads/menu/Nasi_Goreng_Spesial.jpg',
                'description' => 'Nasi goreng dengan campuran telur, ayam, dan sosis.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 4,
                'menu_name' => 'Ayam Penyet Sambal',
                'price' => 20000.00,
                'stock' => 35,
                'status' => 1,
                'image' => 'uploads/menu/Ayam_Penyet_Sambal.jpg',
                'description' => 'Ayam goreng renyah dengan sambal khas yang pedas.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 5,
                'menu_name' => 'Rendang Daging Sapi',
                'price' => 25000.00,
                'stock' => 30,
                'status' => 1,
                'image' => 'uploads/menu/Rendang_Daging_Sapi.jpg',
                'description' => 'Rendang daging sapi yang dimasak perlahan dengan bumbu khas Minang.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 6,
                'menu_name' => 'Pecel Lele',
                'price' => 15000.00,
                'stock' => 50,
                'status' => 1,
                'image' => 'uploads/menu/Pecel_Lele.jpg',
                'description' => 'Ikan lele goreng dengan sambal khas dan lalapan.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 7,
                'menu_name' => 'Ikan Bakar Kecap',
                'price' => 20000.00,
                'stock' => 25,
                'status' => 1,
                'image' => 'uploads/menu/Ikan_Bakar_Kecap.jpg',
                'description' => 'Ikan bakar dengan kecap manis dan bumbu spesial.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            // Kategori 2: Makanan Ringan
            [
                'menu_item_id' => 8,
                'menu_name' => 'Pisang Goreng Keju',
                'price' => 8000.00,
                'stock' => 30,
                'status' => 1,
                'image' => 'uploads/menu/Pisang_Goreng_Keju.jpg',
                'description' => 'Pisang goreng renyah dengan topping keju parut.',
                'category_id' => 2,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 9,
                'menu_name' => 'Tahu Isi',
                'price' => 5000.00,
                'stock' => 40,
                'status' => 1,
                'image' => 'uploads/menu/Tahu_Isi.jpg',
                'description' => 'Tahu goreng renyah dengan isi sayuran segar.',
                'category_id' => 2,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 10,
                'menu_name' => 'Risoles Mayo',
                'price' => 7000.00,
                'stock' => 25,
                'status' => 1,
                'image' => 'uploads/menu/Risoles_Mayo.jpg',
                'description' => 'Risoles dengan isian mayones, daging asap, dan telur.',
                'category_id' => 2,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            // Kategori 3: Minuman
            [
                'menu_item_id' => 11,
                'menu_name' => 'Es Teh Manis',
                'price' => 5000.00,
                'stock' => 60,
                'status' => 1,
                'image' => 'uploads/menu/Es_Teh_Manis.jpg',
                'description' => 'Es teh manis yang menyegarkan.',
                'category_id' => 3,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 12,
                'menu_name' => 'Es Kopi Susu',
                'price' => 12000.00,
                'stock' => 50,
                'status' => 1,
                'image' => 'uploads/menu/Es_Kopi_Susu.jpg',
                'description' => 'Es kopi dengan susu yang creamy dan nikmat.',
                'category_id' => 3,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 13,
                'menu_name' => 'Es Jeruk Segar',
                'price' => 7000.00,
                'stock' => 55,
                'status' => 1,
                'image' => 'uploads/menu/Es_Jeruk_Segar.jpg',
                'description' => 'Jus jeruk segar dengan rasa manis dan asam alami.',
                'category_id' => 3,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 14,
                'menu_name' => 'Teh Tarik',
                'price' => 10000.00,
                'stock' => 40,
                'status' => 1,
                'image' => 'uploads/menu/Teh_Tarik.jpg',
                'description' => 'Teh tarik dengan campuran susu yang khas.',
                'category_id' => 3,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
        ]);
    }
}
