<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class MenuItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $date = Carbon::create(2024, 11, 30, 0, 0, 0);

        DB::table('menu_items')->insert([
            // Category 1: Main Course
            [
                'menu_item_id' => 1,
                'menu_name' => 'Soto Bandung',
                'price' => 15000.00,
                'stock' => 50,
                'status' => 1,
                'image' => 'uploads/menu/Soto_Bandung.jpg',
                'description' => 'Soto Bandung is a traditional Sundanese dish with clear beef broth.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 2,
                'menu_name' => 'Mie Kocok Bandung',
                'price' => 10000.00,
                'stock' => 45,
                'status' => 1,
                'image' => 'uploads/menu/Mie_Kocok_Bandung.jpg',
                'description' => 'Mie Kocok Bandung is a noodle dish with beef broth from Bandung.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 3,
                'menu_name' => 'Special Fried Rice',
                'price' => 18000.00,
                'stock' => 40,
                'status' => 1,
                'image' => 'uploads/menu/Nasi_Goreng_Spesial.jpg',
                'description' => 'Fried rice with a mix of eggs, chicken, and sausage.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 4,
                'menu_name' => 'Spicy Fried Chicken',
                'price' => 20000.00,
                'stock' => 35,
                'status' => 1,
                'image' => 'uploads/menu/Ayam_Penyet_Sambal.jpg',
                'description' => 'Crispy fried chicken with signature spicy sambal sauce.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 5,
                'menu_name' => 'Beef Rendang',
                'price' => 25000.00,
                'stock' => 30,
                'status' => 1,
                'image' => 'uploads/menu/Rendang_Daging_Sapi.jpg',
                'description' => 'Slow-cooked beef rendang with rich Minang spices.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 6,
                'menu_name' => 'Pecel Lele',
                'price' => 15000.00,
                'stock' => 50,
                'status' => 1,
                'image' => 'uploads/menu/Pecel_Lele.jpg',
                'description' => 'Fried catfish with signature sambal and fresh vegetables.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 7,
                'menu_name' => 'Ikan Bakar Kecap',
                'price' => 20000.00,
                'stock' => 25,
                'status' => 1,
                'image' => 'uploads/menu/Ikan_Bakar_Kecap.jpg',
                'description' => 'Grilled fish with sweet soy sauce and special seasoning.',
                'category_id' => 1,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            // Category 2: Snacks
            [
                'menu_item_id' => 8,
                'menu_name' => 'Fried Banana with Cheese',
                'price' => 8000.00,
                'stock' => 30,
                'status' => 1,
                'image' => 'uploads/menu/Pisang_Goreng_Keju.jpg',
                'description' => 'Fried banana with grated cheese topping.',
                'category_id' => 2,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 9,
                'menu_name' => 'Stuffed Tofu',
                'price' => 5000.00,
                'stock' => 40,
                'status' => 1,
                'image' => 'uploads/menu/Tahu_Isi.jpg',
                'description' => 'Crispy fried tofu stuffed with mixed vegetables.',
                'category_id' => 2,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 10,
                'menu_name' => 'Risoles Mayo',
                'price' => 7000.00,
                'stock' => 25,
                'status' => 1,
                'image' => 'uploads/menu/Risoles_Mayo.jpg',
                'description' => 'Risoles filled with mayonnaise, smoked beef, and egg.',
                'category_id' => 2,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            // Category 3: Beverages
            [
                'menu_item_id' => 11,
                'menu_name' => 'Sweet Iced Tea',
                'price' => 5000.00,
                'stock' => 60,
                'status' => 1,
                'image' => 'uploads/menu/Es_Teh_Manis.jpg',
                'description' => 'Refreshing sweet iced tea.',
                'category_id' => 3,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 12,
                'menu_name' => 'Iced Coffee Milk',
                'price' => 12000.00,
                'stock' => 50,
                'status' => 1,
                'image' => 'uploads/menu/Es_Kopi_Susu.jpg',
                'description' => 'Iced coffee with creamy milk.',
                'category_id' => 3,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 13,
                'menu_name' => 'Es Jeruk Segar',
                'price' => 7000.00,
                'stock' => 55,
                'status' => 1,
                'image' => 'uploads/menu/Es_Jeruk_Segar.jpg',
                'description' => 'Fresh orange juice with natural sweet and sour taste.',
                'category_id' => 3,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
            [
                'menu_item_id' => 14,
                'menu_name' => 'Milk Tea',
                'price' => 10000.00,
                'stock' => 40,
                'status' => 1,
                'image' => 'uploads/menu/Teh_Tarik.jpg',
                'description' => 'Milk tea with a signature blend.',
                'category_id' => 3,
                'created_by' => 2,
                'updated_by' => 2,
                'created_at' => $date,
                'updated_at' => $date,
            ],
        ]);
    }
}
